=== Parfait11/XML-Web-Services/meteo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"> 
    <xsd:element name="meteo">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="mesure" minOccurs="1" maxOccurs="30" type="T_MESURE"></xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="T_MESURE">
        <xsd:sequence>
            <xsd:element name="ville" minOccurs="1" maxOccurs="30" type="T_VILLE"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="date" type="xsd:date" use="required"></xsd:attribute>
    </xsd:complexType>
    <xsd:complexType name="T_VILLE">
        <xsd:attribute name="nom" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="temperature" type="xsd:double" use="required"></xsd:attribute>
    </xsd:complexType>
</xsd:schema>

=== Parfait11/XML-Web-Services/meteo2.xml
<?xml version="1.0" encoding="UTF-8"?>
<meteo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/Parfait%20DIMBA/Documents/OxygenXMLEditor/samples/meteo/meteo.xsd">
    <mesure date="2024-11-11">
        <ville nom="casablanca" temperature="22"/>
        <ville nom="Mohammedia" temperature="23"/>
        <ville nom="Marrakech" temperature="32"/>
        <ville nom="Tanger" temperature="25"/>
        <ville nom="El Jadida" temperature="26"/>
        <ville nom="LAAYOUNE" temperature="34"/>
        <ville nom="Ouarzazate" temperature="36"/>
        <ville nom="Dakhla" temperature="34"/>
        <ville nom="Oudja" temperature="31"/>
    </mesure>
    <mesure date="2024-11-12">
        <ville nom="casablanca" temperature="20"/>
        <ville nom="Mohammedia" temperature="21"/>
        <ville nom="Marrakech" temperature="30"/>
        <ville nom="Tanger" temperature="28"/>
        <ville nom="El Jadida" temperature="27"/>
        <ville nom="LAAYOUNE" temperature="32"/>
        <ville nom="Ouarzazate" temperature="32"/>
        <ville nom="Dakhla" temperature="34"/>
        <ville nom="Oudja" temperature="28"/>
    </mesure>
</meteo>
