=== Parfait11/XML-Web-Services/releve.dtd
<!ELEMENT releve (dateReleve, solde, operations)>
<!ATTLIST releve RIB CDATA #REQUIRED>

<!ELEMENT dateReleve (#PCDATA)>

<!ELEMENT solde (#PCDATA)>

<!ELEMENT operations (operation*)>
<!ATTLIST operations dateDebut CDATA #REQUIRED>
<!ATTLIST operations dateFin CDATA #REQUIRED>

<!ELEMENT operation EMPTY>
<!ATTLIST operation type (CREDIT|DEBIT) #REQUIRED>
<!ATTLIST operation date CDATA #REQUIRED>
<!ATTLIST operation montant CDATA #REQUIRED>
<!ATTLIST operation description CDATA #REQUIRED>

=== Parfait11/XML-Web-Services/releve.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE releve SYSTEM "releve.dtd">
<releve RIB="011112222333344445555666">
    <dateReleve>2021-11-10</dateReleve>
    <solde>14500</solde>
    <operations dateDebut="2021-01-01" dateFin="2021-01-30">
        <operation type="CREDIT" date="2021-01-01" montant="9000" description="Vers Espèce"></operation>
        <operation type="DEBIT" date="2021-01-11" montant="3400" description="Chèque Guichet"></operation>
        <operation type="DEBIT" date="2021-01-15" montant="120" description="Prélèvement Assurance"></operation>
        <operation type="CREDIT" date="2021-01-25" montant="70000" description="Virement .."></operation>
    </operations>
</releve>
